on: 
  push: 
    branches: 
      - main 
  pull_request:

permissions: 
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write

jobs: 
  TruffleHog: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Secret Scanning
        id: trufflehog 
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true 

      - name: Scan Results Status 
        if: steps.trufflehog.outcome == 'failure' 
        run: exit 1